# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Docs
  module A_GETTING_STARTED
    # # Getting Started & Crowbar Overview
    #
    # Crowbar is a fast, extensible, and pure-Crystal data transformation, structure-preserving
    # mutation, and feedback-driven evolutionary test generation framework.
    #
    # ### Executive Summary & Key Topics
    #
    # <table>
    #   <thead>
    #     <tr>
    #       <th>Topic</th>
    #       <th>Method / Anchor</th>
    #       <th>Description</th>
    #     </tr>
    #   </thead>
    #   <tbody>
    #     <tr>
    #       <td><strong>Introduction & Architecture</strong></td>
    #       <td><code>.topic_01_introduction</code></td>
    #       <td>Fundamental architectural principles, pipeline modes, and CLI usage.</td>
    #     </tr>
    #   </tbody>
    # </table>
    #
    # ### Related Guides & Source References
    # - shard.yml
    # - src/crowbar.cr
    # - src/cli.cr
    #
    module OVERVIEW
      # **Introduction & Architecture**: Fundamental architectural principles, pipeline modes, and CLI usage.
      #
      # Crowbar operates as both an in-memory transformation library and a high-throughput
      # UNIX streaming filter (`cat input | crowbar > output`).
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Component</th>
      #       <th>Location</th>
      #       <th>Role</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td>Engine</td>
      #       <td>`src/crowbar/engine.cr`</td>
      #       <td>Central pipeline orchestrator</td>
      #     </tr>
      #     <tr>
      #       <td>Mutators</td>
      #       <td>`src/crowbar/mutators/`</td>
      #       <td>Byte, Sequence, Line, Tree, and Value mutators</td>
      #     </tr>
      #     <tr>
      #       <td>Rules</td>
      #       <td>`src/crowbar/rules/`</td>
      #       <td>Syntax-preserving rules for JSON, YAML, HTTP, DNS</td>
      #     </tr>
      #     <tr>
      #       <td>Evolution</td>
      #       <td>`src/crowbar/evolution/`</td>
      #       <td>Genetic algorithm, population corpus, and anti-stagnation</td>
      #     </tr>
      #     <tr>
      #       <td>CLI / TUI</td>
      #       <td>`src/crowbar/cli/`</td>
      #       <td>Opal TrueColor hex diff and streaming CLI</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # #### Command Options & Flags
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Flag / Option</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><code>-n, --count</code></td>
      #       <td>Number of test cases to generate.</td>
      #     </tr>
      #     <tr>
      #       <td><code>-s, --seed</code></td>
      #       <td>Deterministic 64-bit random seed.</td>
      #     </tr>
      #     <tr>
      #       <td><code>-o, --output</code></td>
      #       <td>Output pattern ('out-%n.bin') or '-' for stdout.</td>
      #     </tr>
      #     <tr>
      #       <td><code>-r, --rule</code></td>
      #       <td>Structure-preserving rule (json, yaml, http, dns).</td>
      #     </tr>
      #     <tr>
      #       <td><code>-d, --diff</code></td>
      #       <td>Display Opal TrueColor terminal hex diff.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # #### Working Examples
      #
      # ```crystal
      # # Instant zero-config black-box fuzzing
      # require "crowbar"
      #
      # sample = "Hello World 12345"
      # mutated = Crowbar.fuzz(sample, seed: 42_u64)
      # puts mutated
      # ```
      #
      # #### Common Pitfalls & Safety Caveats
      #
      # - **Warning**: Always provide a deterministic seed if you need exact reproducibility across runs.
      #
      # #### Frequently Asked Questions (FAQ)
      #
      # - **Q: How do I build the documentation site?**
      #   A: Run 'bin/jasper build' followed by 'crystal docs'.
      #
      def self.topic_01_introduction : Nil; end
    end
  end
end
{% end %}
