# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
  module Docs
    module A_GETTING_STARTED
      # # Structure Rules & Advanced Selectors
      #
      # Crowbar 2.0 features 10 structure-preserving format rules and an arsenal of composable selectors
      # to isolate specific data structures or target valid grammars with precision.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Structure-Preserving Rules (10 Formats)</strong></td>
      #       <td><code>.topic_01_rules_catalog</code></td>
      #       <td>Deep inspection of all available format rules in Crowbar.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Composable Selectors & Combinators</strong></td>
      #       <td><code>.topic_02_selectors_and_combinators</code></td>
      #       <td>Target columns, character classes, strides, entropy, or combine with &, |, ~.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/crowbar/selectors/base.cr
      # - src/crowbar/rules/base.cr
      #
      module RULES_AND_SELECTORS
        # **Structure-Preserving Rules (10 Formats)**: Deep inspection of all available format rules in Crowbar.
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Format</th>
        #       <th>Rule Code</th>
        #       <th>Description</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>JSON</td>
        #       <td>`json`</td>
        #       <td>Valid JSON AST with mutated leaf values and bounds</td>
        #     </tr>
        #     <tr>
        #       <td>YAML</td>
        #       <td>`yaml`</td>
        #       <td>Valid YAML document hierarchy with mutated scalars</td>
        #     </tr>
        #     <tr>
        #       <td>HTTP</td>
        #       <td>`http`</td>
        #       <td>RFC HTTP/1.x framing with mutated headers, paths, or body</td>
        #     </tr>
        #     <tr>
        #       <td>DNS</td>
        #       <td>`dns`</td>
        #       <td>RFC 1035 wire-format DNS packets with mutated records</td>
        #     </tr>
        #     <tr>
        #       <td>CSV/TSV</td>
        #       <td>`csv`</td>
        #       <td>RFC 4180 tabular data with column and cell transforms</td>
        #     </tr>
        #     <tr>
        #       <td>XML/HTML</td>
        #       <td>`xml`</td>
        #       <td>Valid XML/HTML document tree with mutated nodes and attributes</td>
        #     </tr>
        #     <tr>
        #       <td>URL</td>
        #       <td>`url`</td>
        #       <td>RFC 3986 URI/URL and query string parameters</td>
        #     </tr>
        #     <tr>
        #       <td>TLV</td>
        #       <td>`tlv`</td>
        #       <td>Type-Length-Value binary packet framing and boundary lengths</td>
        #     </tr>
        #     <tr>
        #       <td>Base64</td>
        #       <td>`base64`</td>
        #       <td>Transparent Base64 envelope decode-mutate-encode</td>
        #     </tr>
        #     <tr>
        #       <td>Varint</td>
        #       <td>`varint`</td>
        #       <td>LEB128/Protobuf 7-bit continuation bit integer streams</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        # #### Working Examples
        #
        # ```
        # fuzzer = Crowbar.define do
        #   preserve :csv # or :xml, :url, :json, :yaml, :http, :dns, :tlv, :base64, :varint
        # end
        # ```
        #
        def self.topic_01_rules_catalog : Nil; end

        # **Composable Selectors & Combinators**: Target columns, character classes, strides, entropy, or combine with &, |, ~.
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Selector</th>
        #       <th>DSL Helper</th>
        #       <th>Description</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>`DelimitedField`</td>
        #       <td>`field: 1, delimiter: ','`</td>
        #       <td>Isolates N-th column or token</td>
        #     </tr>
        #     <tr>
        #       <td>`CharacterClass`</td>
        #       <td>`chars: :digits`</td>
        #       <td>Targets contiguous digits, hex, or printable spans</td>
        #     </tr>
        #     <tr>
        #       <td>`Stride`</td>
        #       <td>`stride: 4, offset: 0`</td>
        #       <td>Targets periodic byte slices at regular intervals</td>
        #     </tr>
        #     <tr>
        #       <td>`Entropy`</td>
        #       <td>`entropy: :high`</td>
        #       <td>Targets Shannon entropy slices (:high or :low)</td>
        #     </tr>
        #     <tr>
        #       <td>`Combinators`</td>
        #       <td>`sel_a & sel_b`</td>
        #       <td>Composable intersection (&), union (</td>
        #       <td>), and inversion (~)</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        # #### Working Examples
        #
        # ```
        # fuzzer = Crowbar.define do
        #   # Intersect delimited field with character class
        #   selector = Crowbar::Selectors::DelimitedField.new(1, ',') &
        #              Crowbar::Selectors::CharacterClass.new(:digits)
        #
        #   scope :numeric_field, selector: selector do
        #     mutate :num, :scale
        #   end
        # end
        # ```
        #
        def self.topic_02_selectors_and_combinators : Nil; end
      end
    end
  end
{% end %}
