# ==============================================================================
# Docs Documentation System - Master Index & Navigation Hub
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# ==============================================================================

{% unless flag?(:release) %}
# The `Docs` module is the authoritative technical reference and documentation guide.
#
# ## Learning Tracks & Topic Index
#
# The documentation is paced into 1 distinct tracks:
#
# ### 1. Getting started (`A_GETTING_STARTED`)
# <table>
#   <thead>
#     <tr>
#       <th>Submodule</th>
#       <th>Title</th>
#       <th>Description</th>
#     </tr>
#   </thead>
#   <tbody>
#     <tr>
#       <td><code>OVERVIEW</code></td>
#       <td><strong>Getting Started & Crowbar Overview</strong></td>
#       <td>Complete introduction to Crowbar 2.0 data transformation and fuzzing architecture.</td>
#     </tr>
#     <tr>
#       <td><code>DSL_GUIDE</code></td>
#       <td><strong>Declarative DSL & Scoped Pipelines</strong></td>
#       <td>In-depth tutorial on composing targeted pipelines, scopes, and fixup hooks.</td>
#     </tr>
#     <tr>
#       <td><code>EVOLUTION_GUIDE</code></td>
#       <td><strong>Feedback-Driven Evolutionary Optimization</strong></td>
#       <td>Guide to the genetic algorithm, population corpus, and anti-stagnation mechanisms.</td>
#     </tr>
#   </tbody>
# </table>
#
module Docs
  # **Quick-Start Commands**: Essential commands for building, running, and testing.
  #
  # #### Docs Commands:
  # ```bash
  # shards install
  # crystal spec
  # crystal docs
  # ```
  def self.topic_01_quick_start : Nil; end

  # **Learning Tracks & Reading Paths**: Curated reading order from beginner to advanced.
  #
  # #### Structured Learning Tracks
  #
  # ##### 1. Getting started (`A_GETTING_STARTED`)
  # - `A_GETTING_STARTED::OVERVIEW`: **Getting Started & Crowbar Overview** &mdash; Complete introduction to Crowbar 2.0 data transformation and fuzzing architecture.
  # - `A_GETTING_STARTED::DSL_GUIDE`: **Declarative DSL & Scoped Pipelines** &mdash; In-depth tutorial on composing targeted pipelines, scopes, and fixup hooks.
  # - `A_GETTING_STARTED::EVOLUTION_GUIDE`: **Feedback-Driven Evolutionary Optimization** &mdash; Guide to the genetic algorithm, population corpus, and anti-stagnation mechanisms.
  #
  def self.topic_02_reading_paths : Nil; end

  # **Master Table of Contents**: Complete hierarchical topic index.
  #
  # #### Complete Documentation Index
  #
  # ##### `A_GETTING_STARTED`
  # - `A_GETTING_STARTED::OVERVIEW`: **Getting Started & Crowbar Overview** &mdash; Complete introduction to Crowbar 2.0 data transformation and fuzzing architecture.
  # - `A_GETTING_STARTED::DSL_GUIDE`: **Declarative DSL & Scoped Pipelines** &mdash; In-depth tutorial on composing targeted pipelines, scopes, and fixup hooks.
  # - `A_GETTING_STARTED::EVOLUTION_GUIDE`: **Feedback-Driven Evolutionary Optimization** &mdash; Guide to the genetic algorithm, population corpus, and anti-stagnation mechanisms.
  #
  def self.topic_03_table_of_contents : Nil; end

  # :nodoc:
  def self.quick_start : Nil; topic_01_quick_start; end
  # :nodoc:
  def self.reading_paths : Nil; topic_02_reading_paths; end
  # :nodoc:
  def self.table_of_contents : Nil; topic_03_table_of_contents; end
end

require "./docs/a_getting_started/overview"
require "./docs/a_getting_started/dsl_guide"
require "./docs/a_getting_started/evolution_guide"
{% end %}
